### PR TITLE
Update according to Contributors library guidelines

### PR DESCRIPTION
**Pull request by JordanMartinez**
This pull request is part of an effort to update and standardize the Contributors libraries according to the [Library Guidelines](https://github.com/purescript-contrib/governance/blob/main/library-guidelines.md). Specifically, it:

1. Adjusts the files and repository structure according to the [repository structure](https://github.com/purescript-contrib/governance/blob/main/library-guidelines.md#repository-structure) section of the guidelines, which includes standard pr templates, issue templates, CI in GitHub Actions, automatic stale issue management, ensures the project uses Spago, and so on.
2. Updates the README and documentation according to the [documentation](https://github.com/purescript-contrib/governance/blob/main/library-guidelines.md#documentation) section of the guidelines. This is a first step towards ensuring Contributors libraries have adequate module documentation, READMEs, a docs directory, and tests (even if just usage examples) in a `test` directory.
3. Updates labels where relevant to help folks better sift through issues on this library and get started contributing.

This PR is the groundwork for followup efforts to ensure contributor libraries are kept up-to-date, documented, tested, and accessible to users and new contributors.

### CODE REVIEW

**Comment by JordanMartinez** [comment]
Note: this currently fails because of the `eslint` rules.

**Comment by thomashoneyman** [comment]
Unless @hdgarrood or @garyb object, we can switch to use `===` for the comparisons (which will fix the linting error)

**Comment by garyb** [comment]
I think the use of `==` is intentional, as that will work for `undefined` as well.

**Review by thomashoneyman — APPROVED** [review]

**Comment by thomashoneyman** [comment]
@garyb I've disabled those rules so the code can remain as-is.

**Comment by garyb** [comment]
I think that's why it was set to `smart` in the prior eslint config: https://eslint.org/docs/2.0.0/rules/eqeqeq#options

I'd forgotten about all this stuff, the JS knowledge is slowly coming back after a long time spent in pure-purescript-land 😆

**Comment by thomashoneyman** [comment]
I'm not particularly familiar with `eslint` 😅 I implemented the standard config based on the most restrictive one I could find in `-contrib`, which was Aff. I would love to make improvements to it if you have any ideas (for example, switching to `smart` by default if you think that's the way to go). The template file is here:

https://github.com/purescript-contrib/governance/blob/main/updater/templates/js/.eslintrc.json

and it's pretty easy to drop a quick update to this library and other libraries using the same config.

**Comment by garyb** [comment]
I think going with the most restrictive one for the template makes sense. Null comparisons aren't all that common in FFI code I imagine (I don't think they should be at least!), so the fact it highlights things like this makes us rethink and reassess what's happening during these updates, which I think is a good thing.

**Comment by thomashoneyman** [comment]
Would you prefer that we switch that rule to `smart` in this repository and remove the comments in the FFI file, or keep the change as-is?

**Comment by garyb** [comment]
Comment works for me, it reiterates that the choice is intentional.

**Pull request merged**
